Django/myapp/blog/urls.py
from django.urls import path
from . import views
# from blog.views import Index

app_name = 'blog'

urlpatterns = [
    # path(패턴, 매핑) /blog/
    # path("", views.index), # FBV
    # 글 목록 조회
    path("", views.Index.as_view(), name='list'), # /blog/    
    # 글 상세 조회
    path("detail/<int:pk>/", views.DetailView.as_view(), name='detail'), # /blog/detail/1
    # 글 작성
    # path("write/", views.write, name = 'write'),
    path("write/", views.Write.as_view(), name='write'), # /blog/write/
    # 글 수정
    path("detail/<int:pk>/edit/", views.Update.as_view(), name='edit'),
    # 글 삭제
    path("detail/<int:pk>/delete/", views.Delete.as_view(), name='delete'),
    # 코멘트 작성
    path("detail/<int:pk>/comment/write", views.CommentWrite.as_view(), name='cm-write'),
    # 코멘트 삭제
    path("detail/<int:pk>/comment/delete", views.CommentDelete.as_view(), name='cm-delete'),
    # 태그 작성
    path("detail/<int:pk>/hashtag/write", views.HashTagWrite.as_view(), name='tag-write'),
    # 태그 삭제
    path("detail/hashtag/<int:pk>/delete", views.HashTagDelete.as_view(), name='tag-delete'),

]

Django/myapp/blog/templates/blog/form_error.html
<!-- form error 출력 -->

<div class="alert alert-danger">
    <ul>
        {% for errors in form.errors.values %}
            {% for error in errors %}
                <li>{{ error }}</li>
            {% endfor %}
        {% endfor %}
    </ul>
    {{ form }}
</div>

Django/myapp/blog/templates/blog/post_detail.html
{% extends 'base.html' %}

{% block content %}

<!-- form error -->
{% if form.errors %}
{% include 'blog/form_error.html' %}
{% else %}
    <h2>제목: {{ post_title }}</h2>

    {% if post.writer == request.user %}
        <a href="{% url 'blog:edit' pk=post_id %}" class="btn border-primary">수정</a>

        <form action="{% url 'blog:delete' pk=post_id %}" method="post">
            {% csrf_token %} 
            <input type="submit" value="삭제" class="btn border-primary">
        </form>
    {% endif %}
    <a href="{% url 'blog:list' %}" class="btn border-primary">목록</a>
    <!-- post_delete.html x -->

    <p>내용 : {{ post_content }}</p>
    <p>작성자 : {{ post_writer }}</p>
    <p>작성일 : {{ post_created_at }}</p>

    <hr>

    <!-- 댓글 작성 화면 -->
    <h3>댓글</h3>
    <form action="{% url 'blog:cm-write' pk=post_id %}" method="post">
        {% csrf_token %}
        {% if comment_form.errors %}
            {% with form=comment_form %}
                {% include 'blog/form_error.html' %}
            {% endwith %}
        {% else %}
            {{ comment_form.content }}
        {% endif %}
            <input type="submit" value="댓글 작성" class="btn btn-primary">
    </form>
    <hr>

    <!-- comments -->
    <!-- if 문 -->
    {% if comments %}
        <!-- for 문 -->
        <ul>
            {% for comment in comments %}
            <!-- 내용, 작성시간, 삭제버튼 -->
                <li>
                    {{ comment.content }} | {{ comment.writer}} | {{ comment.created_at }} | 
                    {% if comment.writer == request.user %}
                        <form action="{% url 'blog:cm-delete' pk=comment.pk %}" method="post">
                            {% csrf_token %}
                            <input type="submit" value="X" class="btn btn-primary">
                        </form>
                    {% endif %}
                </li>
                {% endfor %}
        </ul>
    {% else %}
    <p>댓글이 없습니다.</p>
    {% endif %}
    <hr>

    <!-- 태그 작성 화면 -->
    <!-- hashtags -->
    <h3>해시태그</h3>
    <form action="{% url 'blog:tag-write' pk=post_id %}" method="post">
        {% csrf_token %}
        {% if hashtag_form.name.errors %}
            {% with form=hashtag_form %}
                {% include 'blog/form_error.html' %}
            {% endwith %}
        {% else %}
            {{ hashtag_form.name }}
        {% endif %}
        <input type="submit" value="태그 작성" class="btn btn-primary">
    </form>

    {% if hashtags %}
        <ul>
            {% for hashtag in hashtags %}
                <li>
                    {{ hashtag }} | {{ hashtag.writer }} 
                    {% if hashtag.writer == request.user %}
                        <form action="{% url 'blog:tag-delete' pk=hashtag.pk %}" method="post">
                            {% csrf_token %}
                            <input type="submit" value="X" class="btn btn-primary">
                        </form>
                    {% endif %}
                </li>
                {% endfor %}
        </ul>
    {% else %}
    <p>태그가 없습니다.</p>
    {% endif%}
{% endif %}

{% endblock %}

Django/myapp/blog/templates/blog/post_detail_error.html
<!-- form error 출력 -->
{% comment %}
<div class="alert alert-danger">
    <ul>
        {% for errors in form.errors.values %}
            {% for error in errors %}
                <li>{{ error }}</li>
            {% endfor %}
        {% endfor %}
    </ul>
</div>
{% endcomment %}

{% extends 'base.html' %}

{% block content %}

<!-- form error -->
    <h2>제목: {{ post.title }}</h2>

    {% if post.writer == request.user %}
    <a href="{% url 'blog:edit' pk=post.pk %}" class="btn">수정</a>
    <form action="{% url 'blog:delete' pk=post.pk %}" method="post">
        {% csrf_token %}
        <input type="submit" value="삭제" class="btn">
    </form>
    {% endif %}

    <p>내용: {{ post.content }}</p>
    <p>작성자: {{ post.writer }}</p>
    <p>작성일: {{ post.created_at }}</p>
    <hr>

    <!-- 작성 화면 -->
    <h3>댓글</h3>
    <form action="{% url 'blog:cm-write' pk=post.pk %}" method="post">
        {% csrf_token %}
        {% if comment_form.errors %}
            
        {% else %}
            {{ comment_form.content }}
        {% endif %}
        <input type="submit" value="댓글 작성">
    </form>
    <br>
    <!-- comments -->
    <!-- if 문 -->
    {% if post.comments.all %}
        <!-- for 문 -->
        <ul>
            {% for comment in post.comments.all %}
            <!-- 내용, 작성시간, 삭제 버튼 -->
                <li>{{ comment.content }} / {{ comment.created_at }}
                    {% if comment.writer == request.user %}
                        <form action="{% url 'blog:cm-delete' pk=comment.pk %}" method="post">
                            {% csrf_token %}
                            <input type="submit" value="X" class='btn'>
                        </form>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>댓글이 없습니다.</p>
    {% endif %}
    <hr>
    <!-- 태그작성 화면 -->
    <h3>해시태그</h3>
    <form action="{% url 'blog:tag-write' pk=post.pk %}" method="post">
        {% csrf_token %}
        {{ hashtag_form.name }}
        <input type="submit" value="태그 작성">
    </form>
    {% if post.hashtags.all %}
    <ul>
        {% for hashtag in post.hashtags.all %}
        <li>
            {{ hashtag }}
            {% if hashtag.writer == request.user %}
                <form action="{% url 'blog:tag-delete' pk=hashtag.pk %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="X" class='btn'>
                </form>
            {% endif %}
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <br>
    <p>해시태그가 없습니다.</p>
    {% endif %}

{% endblock %}

Django/myapp/blog/templates/blog/post_edit.html
{% extends 'base.html' %}

{% block content %}
    {% if form.errors %}
        {% include 'blog/form_error.html' %}
    {% else %}
    <form method="post">
        {% csrf_token %} 

        {{ form.title.label_tag }}
        <input 1type="text" name="{{ form.title.name }}" id="" value="{{ form.initial.title }}">
        <br>
        {{ form.content.label_tag }}
        <textarea type="text" name="{{ form.content.name }}" id="">{{ form.initial.content }}</textarea>
        <br>
        <input type="submit">
    </form>
    {% endif %}
{% endblock %}

Django/myapp/blog/templates/blog/post_form.html
{% extends 'base.html' %}

{% block content %}
    <p>블로그 글 작성 화면</p>
    <!-- 제목 -->
    <!-- 내용 -->
    <form action="{% url 'blog:write' %}" method="post">
        {% csrf_token %} 
        <!-- 폼 요청을 허락하겠다. -->
        {{ form.as_p }}
        <input type="submit">
    </form>
    <a href="{% url 'blog:list' %}">목록</a>

{% endblock %}

Django/myapp/blog/templates/blog/post_list.html
{% extends 'base.html' %}

{% block content %}
    <!-- <h1>블로그 게시판 화면</h1> -->
    <p>블로그 게시판 첫 화면입니다.</p>
    <form action="{% url 'blog:write' %}" method="get">
        <input type="hidden" name="{{ redirect_field_name }}" value="{{ request.GET.next }}">
        <input type="submit" value="글 작성">
    </form>
    <!-- <a href="{% url 'blog:write' %}" class="btn btn-outline-success">글 작성</a> -->
    <!-- context -->
    <!-- 조건문, 순회문 -->
    {% if posts %}
    <!-- 글이 있을 때: 테이블 출력 -->
        <table class="table table-bordered">
            <thead class="table-light">
                <tr>
                    <td>제목</td>
                    <td>내용</td>
                    <td>작성자</td>
                    <td>작성일시</td>
                    <td>수정일시</td>
                </tr>
            </thead>
            <tbody>
                {% for post in posts %}
                <tr>
                    <td><a href="{% url 'blog:detail' pk=post.pk %}" class="btn">{{ post.title }}</a></td>
                    <td>{{ post.content }}</td>
                    <td>{{ post.writer }}</td>
                    <td>{{ post.created_at }}</td>
                    <td>{{ post.updated_at }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
    <!-- 글이 없을 때: 문구 출력 -->
        <p>작성된 게시물이 없습니다.</p>
    {% endif %}
    
{% endblock %}